### ISSUE TITLE
不知道該說是bug還是

### ISSUE THREAD

**Issue by EtherZ** [yudachi/plugin-exp-calculator#3]
不是很好截圖說明的bug，舉例描述好了。

列表裏有兩隻LV46的船。
LV46 - 綾波改
LV46 - 陸奧改
選中綾波進行計算，此後一直沒有動過經驗計算器，讓它一直保持顯示綾波的經驗計算結果。
但是綾波升級為LV47後，再打開經驗計算器，這時自動顯示的是LV46的陸奧。

LV47和LV48的時候，因為在這個等級的只有綾波，所以即使從LV47→LV48，計算器顯示的還是綾波的結果。
但是LV48→LV49後，
由於列表裏的排序是
LV49 - 綾波改
LV49 - 島風改
這個順序，結果升級後計算器就自動顯示為島風。

不知道這是一個bug還是本來就是這樣實現的，但是希望計算器能夠一直追蹤顯示被選中的那艘船。

**Comment by Chibaheit** [comment]
为了简单化.你在返回母港时会对经验进行刷新,然后你重选一次就好了..一直追踪没啥实际意义

**Comment by magicae** [comment]
ls will fix it

**Comment by Chibaheit** [comment]
fixed
