### ISSUE TITLE
希望能即时更新舰船的信息

### ISSUE THREAD

**Issue by Wafer-Li** [yudachi/plugin-exp-calculator#4]
计算界面选中一个舰娘之后，下面的“目前等级”等信息不能及时更新，还要选其他的船或者在游戏中进行一次数据交换才能更新到信息，希望能修复这一点。

**Comment by magicae** [comment]
目前只有归港一刻刷新经验 还需要其他哪些时点呢？

**Comment by Wafer-Li** [comment]
其实很多情况下，经验值计算功能只是为了给予玩家一个目标预期。
例如，还有多少级才能改二，还有多少次3-2才能升到那么高级。
所以基本上都不会在出击回港的时候进行经验值计算，反而是在出击之前做一个目标规划。

基于上述理由，希望能在选择舰娘的时候就进行信息的更新

**Comment by magicae** [comment]
我知道你的意思了 点击选择完舰娘下面的数据不会被自动填写是吧？
@Chibaheit

**Comment by Wafer-Li** [comment]
是的

**Comment by Chibaheit** [comment]
fixed
